name: CI/CD Workflow

on:
  push:
    branches:["main"]
  pull_request:
    branches:["main"]

jobs:
  lint:
    name: Run ESLint & Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: action/checkout@v4

      - name: Install node.js
        uses: action/setup-node@v4
        with:
          node-version: [18.x, 20.x, 22.x]
          cache: 'npm'
        
      - name: Install Depedencies
        run: npm install

      - name: Install ESLint
        run: npm run lint

      - name: Install Prettier
        run: npm run format -- --check

type-check:
  name: TypeScript Type Checking
  runs-on: ubuntu-latest
  needs: lint

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      run: vercel --prod --yes --token={{ secret.VERCEL_TOKEN }}