name: CI Pipline

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: action/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel