name: CI Pipline

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/setup-checkout@v4

      - name: Setup Node.js
        uses: action/setup-node$v4
        with:
          node-version: '18'

      - name: Install Depedencies
        run: npm install
      
      - name: Run Tests
        run: npm test